# Generated by Django 4.2.15 on 2024-08-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
