# Generated by Django 4.2.15 on 2024-08-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
