# Generated by Django 4.2.15 on 2024-08-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
