# Generated by Django 4.2.15 on 2024-08-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_book_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
